DROP SEQUENCE EMKO_ARTICLES_ID_SEQ;
DROP TABLE EMKO_ARTICLES_TBL;
DROP SEQUENCE EMKO_USERS_ID_SEQ;
DROP TABLE EMKO_USERS_TBL;

CREATE SEQUENCE EMKO_USERS_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_USERS_TBL (
  user_id NUMBER NOT NULL PRIMARY KEY,
  username VARCHAR2(20) NOT NULL,
  hashpass VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  useralias VARCHAR2(255),
  lastlogindate Date,
  regDate date NOT NULL
);

CREATE SEQUENCE EMKO_ARTICLES_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_ARTICLES_TBL (
  article_id NUMBER NOT NULL PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES EMKO_USERS_TBL(user_id),
  title VARCHAR2(255) NOT NULL,
  type_id NUMBER NOT NULL,
  text VARCHAR2(4000) NOT NULL,
  creationdate date NOT NULL
);

INSERT INTO EMKO_USERS_TBL (USER_ID, USERNAME, HASHPASS, EMAIL, USERALIAS, LASTLOGINDATE, REGDATE) 
  VALUES (EMKO_USERS_ID_SEQ.nextval, 'bobkoo','qwerty12345','john@doe.dk', 'swaggerBoy', 
    TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 
    TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
  );

INSERT INTO EMKO_ARTICLES_TBL(ARTICLE_ID,USER_ID,TITLE, TYPE_ID, TEXT, CREATIONDATE)
 VALUES( EMKO_ARTICLES_ID_SEQ.nextval, 1, 'What is good (news)', 1, 'go to fitness', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 INSERT INTO EMKO_ARTICLES_TBL(ARTICLE_ID,USER_ID,TITLE, TYPE_ID, TEXT, CREATIONDATE)
 VALUES( EMKO_ARTICLES_ID_SEQ.nextval, 1, 'How to gain private', 2, 'go to fitness', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
 COMMIT;
