--Data Definition Language (DDL)
DROP TABLE EMKO_GUESTBOOK_TBL;
DROP SEQUENCE EMKO_GUESTBOOK_ID_SEQ;
DROP TABLE EMKO_TICKETS_TBL;
DROP SEQUENCE EMKO_TICKETS_ID_SEQ;
DROP TABLE EMKO_TICKETTYPES_TBL;
DROP SEQUENCE EMKO_TICKETTYPES_ID_SEQ;
DROP TABLE EMKO_GALLERY_TBL;
DROP SEQUENCE EMKO_GALLERY_ID_SEQ;
DROP TABLE EMKO_ARTICLES_TBL;
DROP SEQUENCE EMKO_ARTICLES_ID_SEQ;
DROP TABLE EMKO_ARTICLETYPES_TBL;
DROP SEQUENCE EMKO_ARTICLETYPES_ID_SEQ;
DROP TABLE EMKO_USERS_TBL;
DROP SEQUENCE EMKO_USERS_ID_SEQ;

CREATE SEQUENCE EMKO_USERS_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_USERS_TBL (
  user_id NUMBER NOT NULL PRIMARY KEY,
  username VARCHAR2(20) NOT NULL,
  hashpass VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL,
  useralias VARCHAR2(255),
  lastlogindate Date,
  regDate date NOT NULL
);

CREATE SEQUENCE EMKO_ARTICLETYPES_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;
  
CREATE TABLE EMKO_ARTICLETYPES_TBL (
  articletype_id NUMBER NOT NULL PRIMARY KEY,
  articletypename VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE EMKO_ARTICLES_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_ARTICLES_TBL (
  article_id NUMBER NOT NULL PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES EMKO_USERS_TBL(user_id),
  title VARCHAR2(255) NOT NULL,
  type_id NUMBER NOT NULL REFERENCES EMKO_ARTICLETYPES_TBL(articletype_id),
  text VARCHAR2(4000) NOT NULL,
  creationdate date NOT NULL
);

CREATE SEQUENCE EMKO_GALLERY_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_GALLERY_TBL (
  galery_id NUMBER NOT NULL PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES EMKO_USERS_TBL(user_id),
  imagepath VARCHAR2(255) NOT NULL,
  creationdate date NOT NULL
);

CREATE SEQUENCE EMKO_TICKETTYPES_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;
  
CREATE TABLE EMKO_TICKETTYPES_TBL (
  tickettype_id NUMBER NOT NULL PRIMARY KEY,
  tickettypename VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE EMKO_TICKETS_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_TICKETS_TBL (
  ticket_id NUMBER NOT NULL PRIMARY KEY,
  title VARCHAR2(255) NOT NULL,
  type_id NUMBER NOT NULL REFERENCES EMKO_TICKETTYPES_TBL(tickettype_id),
  message VARCHAR2(4000) NOT NULL,
  handler_id NUMBER REFERENCES EMKO_USERS_TBL(user_id),
  creationdate date NOT NULL
);

CREATE SEQUENCE EMKO_GUESTBOOK_ID_SEQ
  MINVALUE 1
  MAXVALUE 99999999999999
  START WITH 1
  INCREMENT BY 1;

CREATE TABLE EMKO_GUESTBOOK_TBL (
  gb_id NUMBER NOT NULL PRIMARY KEY,
  guestname VARCHAR2(255) NOT NULL,
  message VARCHAR2(4000) NOT NULL,
  imagepath VARCHAR2(255),
  creationdate date NOT NULL
);

--Data Manipulation Language (DML) 
INSERT INTO EMKO_USERS_TBL (USER_ID, USERNAME, HASHPASS, EMAIL, USERALIAS, LASTLOGINDATE, REGDATE) 
  VALUES (EMKO_USERS_ID_SEQ.nextval, 'bobkoo','qwerty12345','john@doe.dk', 'swaggerBoy', 
    TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 
    TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
  );
  
INSERT INTO EMKO_USERS_TBL (USER_ID, USERNAME, HASHPASS, EMAIL, USERALIAS, LASTLOGINDATE, REGDATE) 
  VALUES (EMKO_USERS_ID_SEQ.nextval, 'emko','barona','john@doe.dk', 'Pedja Medenica', 
    TO_DATE('2004/05/03 22:02:44', 'yyyy/mm/dd hh24:mi:ss'), 
    TO_DATE('2004/05/03 22:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
  );
  
INSERT INTO EMKO_ARTICLETYPES_TBL( ARTICLETYPE_ID, ARTICLETYPENAME)
 VALUES ( EMKO_ARTICLETYPES_ID_SEQ.nextval, 'News' );

INSERT INTO EMKO_ARTICLETYPES_TBL( ARTICLETYPE_ID, ARTICLETYPENAME)
  VALUES ( EMKO_ARTICLETYPES_ID_SEQ.nextval, 'Exercises' );

INSERT INTO EMKO_ARTICLES_TBL(ARTICLE_ID,USER_ID,TITLE, TYPE_ID, TEXT, CREATIONDATE)
 VALUES( EMKO_ARTICLES_ID_SEQ.nextval, 1, 'What is good (news)', 1, 'go to fitness', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
 INSERT INTO EMKO_ARTICLES_TBL(ARTICLE_ID,USER_ID,TITLE, TYPE_ID, TEXT, CREATIONDATE)
  VALUES( EMKO_ARTICLES_ID_SEQ.nextval, 1, 'How to gain private', 2, 'go to fitness', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
 INSERT INTO EMKO_GALLERY_TBL(GALERY_ID, USER_ID, IMAGEPATH, CREATIONDATE)
  VALUES ( EMKO_GALLERY_ID_SEQ.nextval, 1, 'src/image/coolpic.jpg',
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) );
  
INSERT INTO EMKO_GALLERY_TBL(GALERY_ID, USER_ID, IMAGEPATH, CREATIONDATE)
  VALUES ( EMKO_GALLERY_ID_SEQ.nextval, 2, 'src/image/verypic.jpg',
  TO_DATE('2003/05/04 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) );
  
INSERT INTO EMKO_TICKETTYPES_TBL( TICKETTYPE_ID, TICKETTYPENAME)
 VALUES ( EMKO_TICKETTYPES_ID_SEQ.nextval, 'Contacts' );
 
INSERT INTO EMKO_TICKETTYPES_TBL( TICKETTYPE_ID, TICKETTYPENAME)
 VALUES ( EMKO_TICKETTYPES_ID_SEQ.nextval, 'Diets' );
 
INSERT INTO EMKO_TICKETS_TBL(TICKET_ID,TITLE, TYPE_ID, MESSAGE, HANDLER_ID, CREATIONDATE)
  VALUES( EMKO_TICKETS_ID_SEQ.nextval, 'Kak da buda qk', 1, 'Pokaji mi shamane', 1, 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
 INSERT INTO EMKO_TICKETS_TBL(TICKET_ID,TITLE, TYPE_ID, MESSAGE, HANDLER_ID, CREATIONDATE)
  VALUES( EMKO_TICKETS_ID_SEQ.nextval, 'Kvo da qm', 2, 'Pushaci pushaci', 1, 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
INSERT INTO EMKO_GUESTBOOK_TBL(GB_ID,GUESTNAME, MESSAGE, IMAGEPATH, CREATIONDATE)
  VALUES( EMKO_GUESTBOOK_ID_SEQ.nextval, 'Pesho picha', 'Bahti qkiq!!', 'src/pesho.jpg', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
 );
 
INSERT INTO EMKO_GUESTBOOK_TBL(GB_ID,GUESTNAME, MESSAGE, IMAGEPATH, CREATIONDATE)
  VALUES( EMKO_GUESTBOOK_ID_SEQ.nextval, 'Gosho ot pochivka', 'Dneska fen sum ti', '', 
  TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss' ) 
);
 
COMMIT;
